apiVersion: v1
data:
  init_sysctl.sh: |-
    if [[ "$(sysctl -n vm.max_map_count)" -lt 524288 ]]; then
      sysctl -w vm.max_map_count=524288
    fi
    if [[ "$(sysctl -n fs.file-max)" -lt 131072 ]]; then
      sysctl -w fs.file-max=131072
    fi
    if [[ "$(ulimit -n)" != "unlimited" ]]; then
      if [[ "$(ulimit -n)" -lt 131072 ]]; then
        echo "ulimit -n 131072"
        ulimit -n 131072
      fi
    fi
    if [[ "$(ulimit -u)" != "unlimited" ]]; then
      if [[ "$(ulimit -u)" -lt 8192 ]]; then
        echo "ulimit -u 8192"
        ulimit -u 8192
      fi
    fi
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: sonar
    meta.helm.sh/release-namespace: sonar
  creationTimestamp: "2022-06-27T10:30:03Z"
  labels:
    app: sonarqube
    app.kubernetes.io/managed-by: Helm
    chart: sonarqube-4.0.3
    heritage: Helm
    release: sonar
  name: sonar-sonarqube-init-sysctl
  namespace: sonar
  resourceVersion: "94078233"
  uid: cb384f8b-ea67-4cc9-b667-5dde06ceeae0
