apiVersion: v1
data:
  run.sh: |-
    @test "Testing Sonarqube UI is accessible" {
      curl --connect-timeout 5 --retry 12 --retry-delay 1 --retry-max-time 60 sonar-sonarqube:9000/api/system/status
    }
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: sonar
    meta.helm.sh/release-namespace: sonar
  creationTimestamp: "2022-06-27T10:30:03Z"
  labels:
    app: sonarqube
    app.kubernetes.io/managed-by: Helm
    chart: sonarqube-4.0.3
    heritage: Helm
    release: sonar
  name: sonar-sonarqube-tests
  namespace: sonar
  resourceVersion: "94078227"
  uid: f593144e-0ab3-478e-88cc-469850e5eb74
