apiVersion: v1
data:
  postgresql-password: c29uYXJQYXNz
  postgresql-postgres-password: THlPc2FhNHlHVw==
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: sonar
    meta.helm.sh/release-namespace: sonar
  creationTimestamp: "2022-06-27T10:30:03Z"
  labels:
    app.kubernetes.io/instance: sonar
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-10.15.0
  name: sonar-postgresql
  namespace: sonar
  resourceVersion: "94078220"
  uid: 6eadf369-a3ba-4e6f-9249-31b1e1060a4d
type: Opaque
