apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    meta.helm.sh/release-name: sonar
    meta.helm.sh/release-namespace: sonar
  creationTimestamp: "2022-06-27T10:30:03Z"
  labels:
    app: sonarqube
    app.kubernetes.io/managed-by: Helm
    chart: sonarqube-4.0.3
    heritage: Helm
    release: sonar
  name: sonar-sonarqube
  namespace: sonar
  resourceVersion: "94078244"
  uid: d02cc2fa-a7fb-4ecb-b7d1-81664c9a7fe1
spec:
  clusterIP: 10.20.0.217
  clusterIPs:
  - 10.20.0.217
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: http
  selector:
    app: sonarqube
    release: sonar
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
