apiVersion: v1
data:
  repositories: |
    - type: git
      url: https://github.com/vistasunil/tekton-pipeline-example-app.git
    - type: git
      url: https://github.com/vistasunil/tekton-pipeline-example-pipeline.git
    - type: git
      url: https://github.com/vistasunil/tekton-argocd
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-cm","namespace":"argocd"}}
  creationTimestamp: "2022-06-08T09:24:10Z"
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
  resourceVersion: "87165842"
  uid: 633655e8-a3c7-432b-aed6-bae1fba7467a
