apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: Internal
    cloud.google.com/neg: '{"ingress":true}'
    cloud.google.com/neg-status: '{"network_endpoint_groups":{"0":"k8s2-pw2d14lb-argocd-argocd-server-2ix3zpsl"},"zones":["us-east1-b","us-east1-c","us-east1-d"]}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"server","app.kubernetes.io/name":"argocd-server","app.kubernetes.io/part-of":"argocd"},"name":"argocd-server","namespace":"argocd"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":8080},{"name":"https","port":443,"protocol":"TCP","targetPort":8080}],"selector":{"app.kubernetes.io/name":"argocd-server"}}}
    service.kubernetes.io/backend-service: k8s2-pw2d14lb-argocd-argocd-server-2ix3zpsl
    service.kubernetes.io/firewall-rule: k8s2-pw2d14lb-argocd-argocd-server-2ix3zpsl
    service.kubernetes.io/firewall-rule-for-hc: k8s2-pw2d14lb-l4-shared-hc-fw
    service.kubernetes.io/healthcheck: k8s2-pw2d14lb-l4-shared-hc
    service.kubernetes.io/tcp-forwarding-rule: k8s2-tcp-pw2d14lb-argocd-argocd-server-2ix3zpsl
  creationTimestamp: "2022-06-08T09:24:19Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  - gke.networking.io/l4-ilb-v2
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-server
  namespace: argocd
  resourceVersion: "82318517"
  uid: ba76b664-9227-4690-8d9d-f43852386d63
spec:
  clusterIP: 10.20.0.175
  clusterIPs:
  - 10.20.0.175
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30209
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 31471
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.3.193.204
