apiVersion: v1
data:
  additional_jvm_args: -Datlassian.logging.cloud.enabled=false -XX:ActiveProcessorCount=2
  max_heap: 768m
  min_heap: 384m
  reserved_code_cache: 512m
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: jira
    meta.helm.sh/release-namespace: jira
  creationTimestamp: "2022-06-17T12:06:42Z"
  labels:
    app.kubernetes.io/instance: jira
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jira
    app.kubernetes.io/version: 8.20.8
    helm.sh/chart: jira-1.4.0
  name: jira-jvm-config
  namespace: jira
  resourceVersion: "82637362"
  uid: c81a5283-4d8c-4bf4-a8c5-a9bcab0248e1
