apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    meta.helm.sh/release-name: jira
    meta.helm.sh/release-namespace: jira
  creationTimestamp: "2022-06-17T12:06:42Z"
  labels:
    app.kubernetes.io/instance: jira
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jira
    app.kubernetes.io/version: 8.20.8
    helm.sh/chart: jira-1.4.0
  name: jira
  namespace: jira
  resourceVersion: "82637367"
  uid: e213c516-32d3-4f36-bb44-255000178fd4
spec:
  clusterIP: 10.20.0.215
  clusterIPs:
  - 10.20.0.215
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: jira
    app.kubernetes.io/name: jira
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
