apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: jira
    meta.helm.sh/release-namespace: jira
  creationTimestamp: "2022-06-17T12:06:43Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: jira
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jira
    app.kubernetes.io/version: 8.20.8
    helm.sh/chart: jira-1.4.0
  name: jira
  namespace: jira
  resourceVersion: "107876290"
  uid: dfad8460-8d0b-4e92-b28c-c0844a3f894e
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: jira
      app.kubernetes.io/name: jira
  serviceName: jira
  template:
    metadata:
      annotations:
        checksum/config-jvm: f9f88c8383ae3b752aeea61a804493606d3aa779841df32a904c512cd114f8c1
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: jira
        app.kubernetes.io/name: jira
    spec:
      containers:
      - env:
        - name: ATL_PROXY_NAME
          value: jira.int.dev.mykronos.com
        - name: ATL_PROXY_PORT
          value: "80"
        - name: ATL_DB_DRIVER
          value: org.postgresql.Driver
        - name: ATL_JDBC_URL
          value: jdbc:postgresql://10.3.248.183:5432/jiradb
        - name: ATL_JDBC_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: db-secret
        - name: ATL_JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: db-secret
        - name: SET_PERMISSIONS
          value: "true"
        - name: JIRA_SHARED_HOME
          value: /var/atlassian/application-data/shared-home
        - name: JVM_SUPPORT_RECOMMENDED_ARGS
          valueFrom:
            configMapKeyRef:
              key: additional_jvm_args
              name: jira-jvm-config
        - name: JVM_MINIMUM_MEMORY
          valueFrom:
            configMapKeyRef:
              key: min_heap
              name: jira-jvm-config
        - name: JVM_MAXIMUM_MEMORY
          valueFrom:
            configMapKeyRef:
              key: max_heap
              name: jira-jvm-config
        - name: JVM_RESERVED_CODE_CACHE_SIZE
          valueFrom:
            configMapKeyRef:
              key: reserved_code_cache
              name: jira-jvm-config
        image: atlassian/jira-software:8.20.8
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - /shutdown-wait.sh
        name: jira
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 40001
          name: ehcache
          protocol: TCP
        - containerPort: 40011
          name: ehcacheobject
          protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /status
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: "2"
            memory: 2G
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/atlassian/application-data/jira
          name: local-home
        - mountPath: /opt/atlassian/jira/logs
          name: local-home
          subPath: log
        - mountPath: /var/atlassian/application-data/shared-home
          name: shared-home
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - (chgrp 2001 /shared-home; chmod g+w /shared-home)
        image: alpine
        imagePullPolicy: IfNotPresent
        name: nfs-permission-fixer
        resources: {}
        securityContext:
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /shared-home
          name: shared-home
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2001
      serviceAccount: jira
      serviceAccountName: jira
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: shared-home
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: local-home
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: standard
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: jira-6cd74d96cd
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updateRevision: jira-6cd74d96cd
  updatedReplicas: 1
