---
apiVersion: v1
kind: Secret
metadata:
  name: basic-git-app-repo-user-pass
  annotations:
    # Replace <git_repo_url> with your git repo URL (e.g. https://github.com/d0-labs/tekton-pipeline-example-app)
    tekton.dev/git-0: https://github.com/vistasunil/tekton-pipeline-example-app
type: kubernetes.io/basic-auth

---
apiVersion: v1
kind: Secret
metadata:
  name: basic-docker-user-pass
  annotations:
    # Replace <docker_registry_url> with your docker registry URL (e.g. https://my-acr.azurecr.io)
    tekton.dev/docker-0: registry.hub.docker.com/vistasunil
type: kubernetes.io/basic-auth
data:
  password: ZTVjNmI2ZGUtOTJmNy00MmNkLWI3Y2EtNDA0YjczYWViYzZh
  username: dmlzdGFzdW5pbA==

---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-env-secret
