apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: bitbucket-server
    meta.helm.sh/release-namespace: bitbucket
  creationTimestamp: "2022-06-16T11:01:05Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: bitbucket-server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: bitbucket
    app.kubernetes.io/version: 7.21.1
    helm.sh/chart: bitbucket-1.4.0
  name: bitbucket-server
  namespace: bitbucket
  resourceVersion: "107864445"
  uid: 6096eb44-4d2f-43ae-abc1-9e9ff32a79e7
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: bitbucket-server
      app.kubernetes.io/name: bitbucket
  serviceName: bitbucket-server
  template:
    metadata:
      annotations:
        checksum/config-jvm: 53c67d031d160f0ba19a2c9198660d629e056093f8cefbf49d0ea2ab8e34616a
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: bitbucket-server
        app.kubernetes.io/name: bitbucket
    spec:
      containers:
      - env:
        - name: KUBE_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: JAVA_OPTS
          value: -Dcluster.node.name=$(KUBE_POD_NAME)
        - name: JDBC_DRIVER
          value: org.postgresql.Driver
        - name: JDBC_URL
          value: jdbc:postgresql://10.3.248.183:5432/bitbucket
        - name: JDBC_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: db-details
        - name: JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: db-details
        - name: SERVER_PROXY_NAME
          value: bitbucket.int.dev.mykronos.com
        - name: SERVER_PROXY_PORT
          value: "80"
        - name: SETUP_BASEURL
          value: http://bitbucket.int.dev.mykronos.com
        - name: SERVER_CONTEXT_PATH
          value: /
        - name: SERVER_PORT
          value: "7990"
        - name: SET_PERMISSIONS
          value: "true"
        - name: JVM_MINIMUM_MEMORY
          valueFrom:
            configMapKeyRef:
              key: min_heap
              name: bitbucket-server-jvm-config
        - name: JVM_MAXIMUM_MEMORY
          valueFrom:
            configMapKeyRef:
              key: max_heap
              name: bitbucket-server-jvm-config
        - name: JVM_SUPPORT_RECOMMENDED_ARGS
          valueFrom:
            configMapKeyRef:
              key: additional_jvm_args
              name: bitbucket-server-jvm-config
        - name: APPLICATION_MODE
          value: default
        image: atlassian/bitbucket:7.21.1
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - /shutdown-wait.sh
        name: bitbucket
        ports:
        - containerPort: 7990
          name: http
          protocol: TCP
        - containerPort: 7999
          name: ssh
          protocol: TCP
        - containerPort: 5701
          name: hazelcast
          protocol: TCP
        readinessProbe:
          failureThreshold: 60
          httpGet:
            path: /status
            port: 7990
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: "2"
            memory: 2G
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/atlassian/application-data/bitbucket
          name: local-home
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2003
      serviceAccount: bitbucket-server
      serviceAccountName: bitbucket-server
      terminationGracePeriodSeconds: 35
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: local-home
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: standard
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: bitbucket-server-675d6754c5
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updateRevision: bitbucket-server-675d6754c5
  updatedReplicas: 1
