apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: gce-pd-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/gce-pd
  creationTimestamp: "2022-06-15T12:12:03Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    topology.kubernetes.io/region: us-east1
    topology.kubernetes.io/zone: us-east1-c
  name: pvc-cf478145-43db-4225-a86d-f3a38a601266
  resourceVersion: "80395460"
  uid: a50df864-f6a4-4bb9-bb3d-19e5d491f591
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: jenkins-pv-claim
    namespace: jenkins-test
    resourceVersion: "80395438"
    uid: cf478145-43db-4225-a86d-f3a38a601266
  gcePersistentDisk:
    fsType: ext4
    pdName: gke-coe-e955dbc2-dynam-pvc-cf478145-43db-4225-a86d-f3a38a601266
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/region
          operator: In
          values:
          - us-east1
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - us-east1-c
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  volumeMode: Filesystem
status:
  phase: Bound
