apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"labels":{"type":"local"},"name":"jenkins-pv-volume"},"spec":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"10Gi"},"claimRef":{"name":"jenkins-pv-claim","namespace":"jenkins-test"},"local":{"path":"/mnt"},"nodeAffinity":{"required":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"kubernetes.io/hostname","operator":"In","values":["gke-coe-poc-dda8bbe3-gxhl"]}]}]}},"storageClassName":"local-storage"}}
  creationTimestamp: "2022-06-15T11:24:40Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    type: local
  name: jenkins-pv-volume
  resourceVersion: "80395429"
  uid: 8e3edf1d-c000-4b17-85ee-efdf9eaa5739
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: jenkins-pv-claim
    namespace: jenkins-test
    resourceVersion: "80358900"
    uid: 1325a1de-0fbb-4f8a-aca9-d342fc7909f7
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - gke-coe-poc-dda8bbe3-gxhl
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
status:
  phase: Released
