apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: gce-pd-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/gce-pd
  creationTimestamp: "2022-04-04T08:40:11Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    failure-domain.beta.kubernetes.io/region: us-east1
    failure-domain.beta.kubernetes.io/zone: us-east1-c
  name: pvc-b09e16f3-90dd-4fa3-9dba-6c2f62c42f83
  resourceVersion: "20501656"
  uid: 1f854ed5-5b77-4250-95f2-20930ae80569
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: www-web-1
    namespace: default
    resourceVersion: "20501634"
    uid: b09e16f3-90dd-4fa3-9dba-6c2f62c42f83
  gcePersistentDisk:
    fsType: ext4
    pdName: gke-coe-e955dbc2-dynam-pvc-b09e16f3-90dd-4fa3-9dba-6c2f62c42f83
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: failure-domain.beta.kubernetes.io/zone
          operator: In
          values:
          - us-east1-c
        - key: failure-domain.beta.kubernetes.io/region
          operator: In
          values:
          - us-east1
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  volumeMode: Filesystem
status:
  phase: Bound
