apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Kustomize will add the namespace and labels to all files being kustomized
namespace: game-2048
commonLabels:
  pipeline: tekton
  deploy: argocd

resources:
- service.yml
- deployment.yml
- mapping.yml