---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-app-repo-$(uid)
  namespace: tekton-argocd-example
  labels:
    pipeline: tekton
    deploy: argocd
spec:
  params:
  - name: url
    value: $(tt.params.git-app-repo-url)
  - name: revision
    value: $(tt.params.git-app-repo-revision)
  - name: git-app-repo-name
    value: $(tt.params.git-app-repo-name)
  type: git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: image-registry-$(uid)
  namespace: tekton-argocd-example
  labels:
    pipeline: tekton
    deploy: argocd
spec:
  params:
  - name: url
    # Replace <docker_registry_name> with your docker registry name (e.g. my-acr.azurecr.io)
    value: 'registry.hub.docker.com'
  type: image
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: tekton-argocd-example-build-deploy-pipeline-run-
  namespace: tekton-argocd-example
  labels:
    pipeline: tekton
    deploy: argocd
spec:
  serviceAccountName: pipeline-sa
  pipelineRef:
    name: tekton-argocd-example-build-deploy-pipeline
  resources:
  - name: git-app-repo
    resourceRef:
      name: git-app-repo
  - name: image-registry
    resourceRef:
      name: image-registry
