apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Kustomize will add the namespace and labels to all files being kustomized
namespace: tekton-argocd-example
commonLabels:
  pipeline: tekton
  deploy: argocd

resources:
- resources/pipeline-admin-role.yml
- resources/triggers-admin-role.yml
- resources/build-task-cm.yml
- resources/argocd-task-cm.yml
- tasks/build-task.yml
- tasks/argocd-task.yml
- pipelines/build-deploy-pipeline.yml
- triggers/build-deploy-trigger.yml
