apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: growthbook
    meta.helm.sh/release-namespace: growthbook
  creationTimestamp: "2022-06-20T09:18:41Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: growthbook
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: growthbook
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: growthbook-0.1.0
  name: growthbook
  namespace: growthbook
  resourceVersion: "107873972"
  uid: 8bc175ca-9ccd-4b89-9531-432e3a4712cb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: growthbook
      app.kubernetes.io/name: growthbook
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: growthbook
        app.kubernetes.io/name: growthbook
    spec:
      containers:
      - env:
        - name: MONGODB_URI
          value: mongodb://root:password@localhost:27017/
        - name: API_HOST
          value: http://growthbook-api.int.dev.mykronos.com
        - name: APP_ORIGIN
          value: http://growthbook.int.dev.mykronos.com
        image: growthbook/growthbook:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: growthbook
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        - containerPort: 3100
          name: app
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password
        image: mongo:latest
        imagePullPolicy: IfNotPresent
        name: mongo
        ports:
        - containerPort: 27017
          name: mongo
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: uploads-persistent-storage
        persistentVolumeClaim:
          claimName: growthbook-efs-claim
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-06-20T09:18:41Z"
    lastUpdateTime: "2022-06-20T09:18:54Z"
    message: ReplicaSet "growthbook-767997cf7d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-07-09T06:19:31Z"
    lastUpdateTime: "2022-07-09T06:19:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
