apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    meta.helm.sh/release-name: growthbook
    meta.helm.sh/release-namespace: growthbook
  creationTimestamp: "2022-06-20T09:18:41Z"
  labels:
    app.kubernetes.io/instance: growthbook
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: growthbook
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: growthbook-0.1.0
  name: growthbook
  namespace: growthbook
  resourceVersion: "85933150"
  uid: 432ef50a-efc9-4f0d-89e6-6c989d822a29
spec:
  clusterIP: 10.20.0.132
  clusterIPs:
  - 10.20.0.132
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: app
    port: 3100
    protocol: TCP
    targetPort: app
  selector:
    app.kubernetes.io/instance: growthbook
    app.kubernetes.io/name: growthbook
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
